  <!-- Semantic UI -->
  <link rel="stylesheet" type="text/css" href="/semantic/semantic.css"/>

  <!-- Components -->
  <link rel="stylesheet" type="text/css" href="/semantic/components/accordion.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/ad.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/breadcrumb.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/button.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/card.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/checkbox.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/comment.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/container.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/dimmer.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/divider.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/dropdown.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/embed.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/feed.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/flag.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/form.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/grid.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/header.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/icon.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/image.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/input.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/item.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/label.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/list.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/loader.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/menu.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/message.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/modal.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/nag.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/placeholder.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/popup.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/progress.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/rail.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/rating.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/reset.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/reveal.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/search.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/segment.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/shape.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/sidebar.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/site.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/statistic.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/step.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/sticky.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/tab.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/table.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/transition.css"/>
  <link rel="stylesheet" type="text/css" href="/semantic/components/video.css"/>